// apps/web-svelte/src/routes/(provider)/dashboard/earnings/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getProviderEarnings, type ProviderEarnings } from '$lib/provider-api';
	import { formatMoney } from '$lib/currency-display';
	import { formatDate } from '$lib/utils';

	let data = $state<ProviderEarnings | null>(null);
	let loading = $state(true);
	let error = $state(false);

	function load(): void {
		loading = true;
		error = false;
		void (async () => {
			try {
				data = await getProviderEarnings();
			} catch {
				error = true;
			} finally {
				loading = false;
			}
		})();
	}

	onMount(load);

	const maxMonthly = $derived(data ? Math.max(1, ...data.monthly.map((m) => m.revenue)) : 1);
</script>

<div class="space-y-6">
	<div>
		<h1 class="text-3xl font-bold tracking-tight text-slate-900">Earnings</h1>
		<p class="mt-1 text-sm text-slate-500">Revenue, commission and payouts across the last 12 months.</p>
	</div>

	{#if loading}
		<div class="grid grid-cols-3 gap-4">
			{#each Array(3) as _, i (i)}
				<div class="h-28 animate-pulse rounded-2xl border border-slate-100 bg-white"></div>
			{/each}
		</div>
	{:else if error}
		<div class="rounded-2xl border border-red-200 bg-red-50 p-8 text-center">
			<p class="text-sm text-red-600">Could not load earnings.</p>
			<button
				type="button"
				onclick={load}
				class="mt-4 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700 transition hover:bg-slate-50"
			>
				Try Again
			</button>
		</div>
	{:else if data}
		<div class="grid grid-cols-3 gap-4">
			<div class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
				<p class="text-[11px] font-semibold tracking-wide text-slate-400 uppercase">Total revenue</p>
				<p class="mt-1.5 text-2xl font-bold text-slate-900">{formatMoney(data.allTime.revenue, 'USD')}</p>
			</div>
			<div class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
				<p class="text-[11px] font-semibold tracking-wide text-slate-400 uppercase">Commission</p>
				<p class="mt-1.5 text-2xl font-bold text-slate-900">{formatMoney(data.allTime.commission, 'USD')}</p>
			</div>
			<div class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
				<p class="text-[11px] font-semibold tracking-wide text-slate-400 uppercase">Your payout</p>
				<p class="mt-1.5 text-2xl font-bold text-emerald-700">{formatMoney(data.allTime.payout, 'USD')}</p>
			</div>
		</div>

		<div class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
			<h2 class="text-sm font-bold text-slate-900">Monthly revenue — last 12 months</h2>
			<div class="mt-4 flex h-48 items-end gap-1.5">
				{#each data.monthly as m (m.month)}
					<div class="flex flex-1 flex-col items-center gap-1">
						<span class="text-[9px] font-semibold text-slate-400">
							{m.revenue > 0 ? formatMoney(m.revenue, 'USD') : ''}
						</span>
						<div
							class="w-full rounded-t-md bg-[#1D8D2B]/80"
							style="height: {Math.max(4, (m.revenue / maxMonthly) * 160)}px"
						></div>
						<span class="text-[9px] font-semibold text-slate-400">{m.month.slice(5)}</span>
					</div>
				{/each}
			</div>
		</div>

		<div class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm">
			<h2 class="text-sm font-bold text-slate-900">Recent payouts</h2>
			{#if data.recentPayouts.length === 0}
				<p class="mt-4 text-sm text-slate-400">No payouts yet.</p>
			{:else}
				<div class="mt-4 divide-y divide-slate-100">
					{#each data.recentPayouts as p (p.id)}
						<div class="flex items-center justify-between gap-2 py-3">
							<div>
								<p class="text-sm font-semibold text-slate-800">{p.listingName}</p>
								<p class="text-xs text-slate-400">
									{p.reference} · {p.confirmedAt ? formatDate(p.confirmedAt) : ''}
								</p>
							</div>
							<div class="text-right">
								<p class="text-sm font-bold text-slate-900">{formatMoney(p.payout, p.currency)}</p>
								<p class="text-[10px] text-slate-400">of {formatMoney(p.totalAmount, p.currency)}</p>
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	{/if}
</div>

// apps/web/app/(provider)/dashboard/earnings/page.tsx
"use client";

import { useQuery } from "@tanstack/react-query";
import { DollarSign, TrendingUp, Percent, Calendar } from "lucide-react";
import { listingApi } from "@/lib/listing-api";
import { Card, SectionHeader, CardHeader } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { DataTable, type Column } from "@/components/tables/DataTable";
import { StatCard, RevenueBarChart } from "@/components/charts/Charts";
import { formatCurrency, formatDate, formatMonthLabel } from "@/lib/utils";
import type { EarningsData } from "@/types/provider";

const fetchEarnings = () =>
  listingApi
    .get<{ success: boolean; data: EarningsData }>("/provider/earnings")
    .then((r) => r.data.data);

export default function EarningsPage() {
  const { data, isLoading } = useQuery({
    queryKey: ["provider-earnings"],
    queryFn:  fetchEarnings,
    staleTime: 5 * 60_000,
  });

  const monthlyChartData = (data?.monthly ?? []).slice(-6).map((m) => ({
    label: formatMonthLabel(m.month),
    revenue: m.payout,
  }));

  const columns: Column<EarningsData["recentPayouts"][0]>[] = [
    {
      key: "listing",
      label: "Listing",
      render: (p) => (
        <div>
          <p className="text-sm font-medium text-slate-900 truncate max-w-[200px]">{p.listingName ?? "—"}</p>
          <span className="text-xs text-slate-400 capitalize">{p.category}</span>
        </div>
      ),
    },
    {
      key: "ref",
      label: "Reference",
      render: (p) => <code className="text-xs text-slate-600 font-mono">{p.reference}</code>,
    },
    {
      key: "total",
      label: "Total Charged",
      render: (p) => (
        <span className="text-sm text-slate-700">{formatCurrency(p.totalAmount, p.currency)}</span>
      ),
    },
    {
      key: "commission",
      label: "Commission",
      render: (p) => (
        <span className="text-sm text-slate-500">-{formatCurrency(p.commission, p.currency)}</span>
      ),
    },
    {
      key: "payout",
      label: "Your Payout",
      render: (p) => (
        <span className="text-sm font-bold text-emerald-700">{formatCurrency(p.payout, p.currency)}</span>
      ),
    },
    {
      key: "status",
      label: "Status",
      render: (p) => <Badge label={p.status} status={p.status} />,
    },
    {
      key: "date",
      label: "Confirmed",
      render: (p) => <span className="text-xs text-slate-400">{formatDate(p.confirmedAt)}</span>,
    },
  ];

  return (
    <div className="space-y-5 animate-fade-in">
      <SectionHeader
        title="Earnings & Payouts"
        subtitle="Track your revenue, commissions, and provider payouts"
      />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <StatCard
          title="Total Revenue Generated"
          value={formatCurrency(data?.allTime.revenue ?? 0)}
          subtitle="Gross booking value"
          icon={<DollarSign />}
          color="blue"
          loading={isLoading}
        />
        <StatCard
          title="Platform Commission"
          value={formatCurrency(data?.allTime.commission ?? 0)}
          subtitle="ZikaBooking fees deducted"
          icon={<Percent />}
          color="amber"
          loading={isLoading}
        />
        <StatCard
          title="Net Payout to You"
          value={formatCurrency(data?.allTime.payout ?? 0)}
          subtitle="After commission"
          icon={<TrendingUp />}
          color="emerald"
          loading={isLoading}
        />
      </div>

      <Card>
        <CardHeader
          title="Monthly Payout Trend"
          subtitle="Last 6 months"
          icon={<Calendar />}
        />
        {isLoading ? (
          <div className="h-48 bg-slate-50 rounded-xl animate-shimmer" />
        ) : (
          <RevenueBarChart data={monthlyChartData} />
        )}
      </Card>

      <Card>
        <CardHeader title="Monthly Breakdown" icon={<TrendingUp />} />
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border">
                {["Month", "Bookings", "Revenue", "Commission", "Payout"].map((h) => (
                  <th key={h} className="text-left py-3 px-4 text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {isLoading
                ? Array.from({ length: 6 }).map((_, i) => (
                    <tr key={i}>
                      {Array.from({ length: 5 }).map((_, j) => (
                        <td key={j} className="py-3 px-4">
                          <div className="h-4 bg-slate-100 rounded animate-shimmer" />
                        </td>
                      ))}
                    </tr>
                  ))
                : (data?.monthly ?? []).slice().reverse().map((m) => (
                    <tr key={m.month} className="hover:bg-surface-subtle transition-colors">
                      <td className="py-3 px-4 font-medium text-slate-900">{formatMonthLabel(m.month)}</td>
                      <td className="py-3 px-4 text-slate-600">{m.bookings}</td>
                      <td className="py-3 px-4 text-slate-700">{formatCurrency(m.revenue)}</td>
                      <td className="py-3 px-4 text-slate-500">-{formatCurrency(m.commission)}</td>
                      <td className="py-3 px-4 font-bold text-emerald-700">{formatCurrency(m.payout)}</td>
                    </tr>
                  ))
              }
            </tbody>
          </table>
        </div>
      </Card>

      <Card padding="none">
        <div className="p-5 border-b border-border">
          <h3 className="font-semibold text-slate-900">Recent Transactions</h3>
          <p className="text-xs text-slate-500 mt-0.5">Latest confirmed bookings</p>
        </div>
        <DataTable
          columns={columns}
          data={data?.recentPayouts ?? []}
          keyExtractor={(p) => p.id}
          loading={isLoading}
          emptyTitle="No payouts yet"
          emptyMessage="Completed bookings will appear as payout records."
        />
      </Card>
    </div>
  );
}
