// apps/web-svelte/src/routes/auth/reset-password/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { resetPassword, validatePassword, AuthApiError } from '$lib/auth-api';
	import { setSession } from '$lib/stores/auth.svelte';
	import AuthCard from '../AuthCard.svelte';

	const token = $derived(page.url.searchParams.get('token') ?? '');
	let password = $state('');
	let confirmPassword = $state('');
	let showPassword = $state(false);
	let errors = $state<Record<string, string | undefined>>({});
	let submitting = $state(false);

	function handleSubmit(): void {
		const fe: Record<string, string | undefined> = {};
		const passwordErr = validatePassword(password);
		if (passwordErr) {
			fe.password = passwordErr;
		} else if (password !== confirmPassword) {
			fe.confirmPassword = 'Passwords do not match';
		}
		errors = fe;
		if (Object.values(fe).some(Boolean)) return;

		submitting = true;
		void (async () => {
			try {
				const data = await resetPassword({ token, password, confirmPassword });
				setSession(data.tokens.accessToken, data.user);
				await goto('/');
			} catch (err) {
				if (err instanceof AuthApiError) {
					if (err.code === 'TOKEN_EXPIRED') {
						errors = { general: 'This password reset link has expired. Please request a new one.' };
					} else if (err.code === 'TOKEN_USED') {
						errors = { general: 'This reset link has already been used.' };
					} else if (err.fields) {
						errors = err.fields;
					} else {
						errors = { general: err.message ?? 'Something went wrong.' };
					}
				} else {
					errors = { general: 'Something went wrong.' };
				}
			} finally {
				submitting = false;
			}
		})();
	}
</script>

{#if !token}
	<AuthCard>
		<div class="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm">
			<div class="mb-4 text-5xl">❌</div>
			<h1 class="mb-2 text-xl font-bold text-slate-900">Invalid link</h1>
			<p class="mb-4 text-slate-500">This password reset link is invalid.</p>
			<a href="/auth/forgot-password" class="font-semibold text-[#1D8D2B] hover:underline">
				Request a new link
			</a>
		</div>
	</AuthCard>
{:else}
	<AuthCard>
		<div class="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm">
			<h1 class="text-2xl font-bold text-slate-900">Set new password</h1>
			<p class="mt-1 mb-6 text-sm text-slate-500">Choose a strong password for your account.</p>

			<form
				onsubmit={(e) => {
					e.preventDefault();
					handleSubmit();
				}}
				class="space-y-4"
			>
				<div>
					<label for="reset-password" class="mb-1.5 block text-sm font-medium text-slate-700">
						New password
					</label>
					<div class="relative">
						<input
							id="reset-password"
							type={showPassword ? 'text' : 'password'}
							bind:value={password}
							placeholder="Min. 8 characters"
							autocomplete="new-password"
							class="w-full rounded-xl border bg-[#f6fdf8] px-4 py-3 pr-11 text-sm transition focus:border-[#1D8D2B] focus:ring-2 focus:ring-[#1D8D2B]/25 focus:outline-none {errors.password
								? 'border-red-400'
								: 'border-slate-200'}"
						/>
						<button
							type="button"
							tabindex="-1"
							onclick={() => (showPassword = !showPassword)}
							class="absolute top-1/2 right-3.5 -translate-y-1/2 text-slate-400 hover:text-slate-600"
							aria-label={showPassword ? 'Hide password' : 'Show password'}
						>
							{showPassword ? '🙈' : '👁️'}
						</button>
					</div>
					{#if errors.password}
						<p class="mt-1 text-xs text-red-500">{errors.password}</p>
					{/if}
				</div>

				<div>
					<label for="reset-confirm" class="mb-1.5 block text-sm font-medium text-slate-700">
						Confirm new password
					</label>
					<input
						id="reset-confirm"
						type="password"
						bind:value={confirmPassword}
						placeholder="Repeat password"
						autocomplete="new-password"
						class="w-full rounded-xl border bg-[#f6fdf8] px-4 py-3 text-sm transition focus:border-[#1D8D2B] focus:ring-2 focus:ring-[#1D8D2B]/25 focus:outline-none {errors.confirmPassword
							? 'border-red-400'
							: 'border-slate-200'}"
					/>
					{#if errors.confirmPassword}
						<p class="mt-1 text-xs text-red-500">{errors.confirmPassword}</p>
					{/if}
				</div>

				{#if errors.general}
					<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3">
						<p class="text-sm text-red-600">{errors.general}</p>
						{#if errors.general.includes('expired')}
							<a
								href="/auth/forgot-password"
								class="mt-1 block text-sm font-semibold text-[#1D8D2B]"
							>
								Request a new link →
							</a>
						{/if}
					</div>
				{/if}

				<button
					type="submit"
					disabled={submitting}
					class="flex w-full items-center justify-center gap-2 rounded-xl bg-[#0c2614] py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-[#081b0d] disabled:cursor-not-allowed disabled:opacity-60"
				>
					{#if submitting}
						<span class="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"
						></span>
					{/if}
					Set new password
				</button>
			</form>
		</div>
	</AuthCard>
{/if}

// apps/mobile/app/(auth)/reset-password.tsx
import { useState } from "react";
import { View, Text, KeyboardAvoidingView, Platform, ScrollView, Alert } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { useMutation } from "@tanstack/react-query";
import { api } from "../../lib/api";
import { useAuthStore } from "../../store/auth";
import { FormField } from "../../components/ui/FormField";
import { Button } from "../../components/ui/Button";
import { handleRoleAndStatusRedirect } from "./login";
import type { ApiResponse, AuthResponse } from "@zika/types";

export default function ResetPasswordScreen() {
  // Token comes from deep link: zikabooking://reset-password?token=...
  const { token } = useLocalSearchParams<{ token?: string }>();
  const [form, setForm] = useState({ password: "", confirmPassword: "" });
  const [errors, setErrors] = useState<{ password?: string; confirmPassword?: string; general?: string }>({});
  const setAuth = useAuthStore((s) => s.setAuth);

  const mutation = useMutation({
    mutationFn: async () => {
      if (!token) throw new Error("Missing token");
      const res = await api.post<ApiResponse<AuthResponse & { message: string }>>("/auth/reset-password", {
        token, password: form.password, confirmPassword: form.confirmPassword,
      });
      if (!res.data.success) throw res.data;
      return res.data.data;
    },
    onSuccess: async (data) => {
      await setAuth(data.user, data.tokens.accessToken);
      Alert.alert("Success", "Your password has been updated. You're now signed in.");
      handleRoleAndStatusRedirect(data.user);
    },
    onError: (err: unknown) => {
      const data = (err as { error?: { code?: string; message?: string; fields?: Record<string, string> } }).error;
      if (data?.code === "TOKEN_EXPIRED") {
        setErrors({ general: "This password reset link has expired. Please request a new one." });
      } else if (data?.code === "TOKEN_USED") {
        setErrors({ general: "This reset link has already been used. Please request a new one." });
      } else if (data?.fields) {
        setErrors(data.fields as typeof errors);
      } else {
        setErrors({ general: data?.message ?? "Something went wrong. Please try again." });
      }
    },
  });

  function handleSubmit() {
    if (form.password.length < 8) { setErrors({ password: "Password must be at least 8 characters." }); return; }
    if (form.password !== form.confirmPassword) { setErrors({ confirmPassword: "Passwords do not match." }); return; }
    setErrors({});
    mutation.mutate();
  }

  if (!token) {
    return (
      <View className="flex-1 bg-white items-center justify-center px-6">
        <Text className="text-xl font-bold text-gray-900 mb-2">Invalid link</Text>
        <Text className="text-gray-500 text-center">This password reset link is invalid. Please request a new one.</Text>
      </View>
    );
  }

  return (
    <KeyboardAvoidingView className="flex-1 bg-white" behavior={Platform.OS === "ios" ? "padding" : undefined}>
      <ScrollView contentContainerStyle={{ padding: 24, paddingTop: 80 }} keyboardShouldPersistTaps="handled">
        <Text className="text-3xl font-bold text-gray-900 mb-1">Set new password</Text>
        <Text className="text-base text-gray-500 mb-8">Choose a strong password for your account.</Text>

        <FormField label="New password" value={form.password}
          onChangeText={(v) => { setForm((p) => ({ ...p, password: v })); setErrors({}); }}
          error={errors.password} placeholder="Min. 8 characters" secureTextEntry />

        <FormField label="Confirm new password" value={form.confirmPassword}
          onChangeText={(v) => { setForm((p) => ({ ...p, confirmPassword: v })); setErrors({}); }}
          error={errors.confirmPassword} placeholder="Repeat password" secureTextEntry
          returnKeyType="done" onSubmitEditing={handleSubmit} />

        {errors.general ? (
          <View className="bg-red-50 border border-red-200 rounded-lg px-4 py-3 mb-4">
            <Text className="text-red-600 text-sm">{errors.general}</Text>
          </View>
        ) : null}

        <Button title="Set new password" onPress={handleSubmit} loading={mutation.isPending} />
      </ScrollView>
    </KeyboardAvoidingView>
  );
}
