// apps/web-svelte/src/routes/auth/verify-pending/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { resendVerification, AuthApiError } from '$lib/auth-api';
	import AuthCard from '../AuthCard.svelte';

	const email = $derived(page.url.searchParams.get('email') ?? '');
	let success = $state(false);
	let error = $state<string | null>(null);
	let sending = $state(false);

	function handleResend(): void {
		error = null;
		sending = true;
		void (async () => {
			try {
				await resendVerification(email);
				success = true;
			} catch (err) {
				error = err instanceof AuthApiError ? err.message : 'Failed to resend verification email.';
			} finally {
				sending = false;
			}
		})();
	}
</script>

<AuthCard>
	<div class="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm">
		<div class="mb-4 text-5xl">✉️</div>
		<h1 class="mb-2 text-2xl font-bold text-slate-900">Verify your email</h1>
		<p class="mb-6 text-slate-500">
			A verification link was sent to
			<strong class="text-slate-800">{email || 'your email'}</strong>. Please click the link to
			activate your account.
		</p>

		{#if success}
			<div class="mb-6 rounded-lg border border-green-200 bg-green-50 px-4 py-3">
				<p class="text-sm text-green-600">A new verification link has been sent!</p>
			</div>
		{/if}

		{#if error}
			<div class="mb-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3">
				<p class="text-sm text-red-600">{error}</p>
			</div>
		{/if}

		<button
			type="button"
			onclick={handleResend}
			disabled={!email || success || sending}
			class="mb-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0c2614] py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-[#081b0d] disabled:cursor-not-allowed disabled:opacity-60"
		>
			{#if sending}
				<span class="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"
				></span>
			{/if}
			Resend verification email
		</button>

		<a href="/auth/login" class="block text-sm font-semibold text-[#1D8D2B] hover:underline">
			Back to Sign In
		</a>
	</div>
</AuthCard>

// apps/mobile/app/(auth)/verify-pending.tsx
import { useState, useEffect } from "react";
import { View, Text, Alert } from "react-native";
import { useLocalSearchParams, Link } from "expo-router";
import { useMutation } from "@tanstack/react-query";
import { api } from "../../lib/api";
import { Button } from "../../components/ui/Button";

export default function VerifyPendingScreen() {
  const { email } = useLocalSearchParams<{ email: string }>();
  const [cooldown, setCooldown] = useState(0);

  useEffect(() => {
    if (cooldown <= 0) return;
    const t = setTimeout(() => setCooldown((c) => c - 1), 1000);
    return () => clearTimeout(t);
  }, [cooldown]);

  const resendMutation = useMutation({
    mutationFn: async () => {
      await api.post("/auth/resend-verification", { email });
    },
    onSuccess: () => {
      setCooldown(60);
      Alert.alert("Sent!", "A new verification email has been sent. Please check your inbox.");
    },
    onError: (err: unknown) => {
      const data = (err as { response?: { data?: { error?: { code?: string } } } }).response?.data;
      if (data?.error?.code === "COOLDOWN") {
        setCooldown(60);
      } else if (data?.error?.code === "RATE_LIMITED") {
        Alert.alert("Limit reached", "You've requested the maximum number of verification emails. Please try again later or contact support.");
      } else {
        Alert.alert("Error", "Something went wrong. Please try again.");
      }
    },
  });

  return (
    <View className="flex-1 bg-white items-center justify-center px-6">
      <Text className="text-5xl mb-4">✉️</Text>
      <Text className="text-2xl font-bold text-gray-900 text-center mb-2">Verify your email</Text>
      <Text className="text-base text-gray-500 text-center mb-2">
        We sent a verification link to
      </Text>
      <Text className="text-base font-semibold text-gray-800 text-center mb-6">{email}</Text>
      <Text className="text-sm text-gray-400 text-center mb-8">
        Click the link in the email to activate your account. Check your spam folder if you don't see it.
      </Text>

      <Button
        title={cooldown > 0 ? `Resend in ${cooldown}s` : "Resend verification email"}
        variant="secondary"
        onPress={() => resendMutation.mutate()}
        loading={resendMutation.isPending}
        disabled={cooldown > 0}
      />

      <Link href="/(auth)/login" className="mt-6 text-primary font-semibold text-base text-center">
        Back to Sign In
      </Link>
    </View>
  );
}
