// apps/mobile/app/verify.tsx
import { useEffect, useState } from "react";
import {
  View,
  Text,
  ActivityIndicator,
  TouchableOpacity,
  StyleSheet,
  Image,
} from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { useMutation } from "@tanstack/react-query";
import { api } from "../lib/api";
import { useAuthStore } from "../store/auth";
import { handlePostAuthRedirect } from "./(auth)/login";
import { K } from "../constants/theme";
import type { ApiResponse, AuthResponse } from "@zika/types";

type VerifyState =
  | "verifying"
  | "success"
  | "already_verified"
  | "expired"
  | "used"
  | "invalid"
  | "error";

export default function VerifyScreen() {
  const { token } = useLocalSearchParams<{ token?: string }>();
  const setAuth = useAuthStore((s) => s.setAuth);
  const [state, setState] = useState<VerifyState>(token ? "verifying" : "invalid");

  const mutation = useMutation({
    mutationFn: async (t: string) => {
      const res = await api.get<ApiResponse<AuthResponse & { message: string }>>(
        "auth/verify",
        { params: { token: t } },
      );
      if (!res.data.success) throw res.data;
      return res.data.data;
    },
    onSuccess: async (data) => {
      await setAuth(data.user, data.tokens.accessToken);
      const isAlready = (data.message ?? "").toLowerCase().includes("already");
      setState(isAlready ? "already_verified" : "success");
      setTimeout(() => handlePostAuthRedirect(data.user), 1500);
    },
    onError: (err: unknown) => {
      const code =
        (err as any)?.error?.code ??
        (err as any)?.response?.data?.error?.code ??
        "";
      if (code === "TOKEN_EXPIRED") setState("expired");
      else if (code === "TOKEN_USED" || code === "ALREADY_VERIFIED") setState("used");
      else if (code === "INVALID_TOKEN") setState("invalid");
      else setState("error");
    },
  });

  useEffect(() => {
    if (!token) return;
    mutation.mutate(token);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  type StateContent = {
    emoji: string;
    title: string;
    body: string;
    action?: { label: string; onPress: () => void };
  };

  const content: Record<VerifyState, StateContent> = {
    verifying: {
      emoji: "",
      title: "Verifying your email…",
      body: "Please wait a moment.",
    },
    success: {
      emoji: "🎉",
      title: "Email verified!",
      body: "Welcome to Kainook! Taking you in…",
    },
    already_verified: {
      emoji: "✅",
      title: "Already verified",
      body: "Your email is already verified. Taking you in…",
    },
    expired: {
      emoji: "⌛",
      title: "Link expired",
      body: "This verification link has expired. Links are valid for 24 hours. Please sign in and request a new one.",
      action: {
        label: "Back to Sign In",
        onPress: () => router.replace("/(auth)/login"),
      },
    },
    used: {
      emoji: "🔒",
      title: "Link already used",
      body: "This verification link has already been used. If your email is verified, you can sign in now.",
      action: {
        label: "Sign In",
        onPress: () => router.replace("/(auth)/login"),
      },
    },
    invalid: {
      emoji: "❌",
      title: "Invalid link",
      body: "This verification link is invalid or incomplete. Please check your email and try again.",
      action: {
        label: "Back to Sign In",
        onPress: () => router.replace("/(auth)/login"),
      },
    },
    error: {
      emoji: "⚠️",
      title: "Something went wrong",
      body: "We couldn't verify your email. Please try tapping the link again, or request a new verification email.",
      action: {
        label: "Back to Sign In",
        onPress: () => router.replace("/(auth)/login"),
      },
    },
  };

  const c = content[state];

  return (
    <View style={styles.container}>
      <View style={styles.logoContainer}>
        <Image
          source={require("../assets/logo.png")}
          style={styles.logoImage}
          resizeMode="contain"
        />
      </View>

      {state === "verifying" ? (
        <ActivityIndicator
          color={K.colors.accent}
          size="large"
          style={styles.spinner}
        />
      ) : (
        <Text style={styles.emoji}>{c.emoji}</Text>
      )}

      <Text style={styles.title}>{c.title}</Text>
      <Text style={styles.body}>{c.body}</Text>

      {c.action && (
        <TouchableOpacity
          style={styles.btn}
          onPress={c.action.onPress}
          activeOpacity={0.85}
        >
          <Text style={styles.btnText}>{c.action.label}</Text>
        </TouchableOpacity>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: K.colors.darkGreen,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  logoContainer: {
    width: 90,
    height: 90,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  logoImage: { width: 80, height: 80 },
  spinner: { marginBottom: 24 },
  emoji: { fontSize: 56, marginBottom: 16 },
  title: {
    fontSize: K.font.xxl,
    fontWeight: "800",
    color: "#fff",
    textAlign: "center",
    marginBottom: 12,
  },
  body: {
    fontSize: K.font.base,
    color: K.colors.textLightMuted,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 32,
  },
  btn: {
    backgroundColor: K.colors.accent,
    borderRadius: K.radius.md,
    paddingVertical: 14,
    paddingHorizontal: 40,
  },
  btnText: { color: "#fff", fontSize: K.font.base, fontWeight: "700" },
});

// apps/web-svelte/src/routes/verify/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { verifyEmail, AuthApiError } from '$lib/auth-api';
	import { setSession } from '$lib/stores/auth.svelte';

	let status = $state('loading');
	let email = $state<string | null>(null);
	const token = $derived(page.url.searchParams.get('token') ?? '');

	onMount(() => {
		if (!token || token.length !== 64) {
			status = 'invalid';
			return;
		}
		void (async () => {
			try {
				const data = await verifyEmail(token);
				setSession(data.tokens.accessToken, data.user);
				status = data.message.includes('already') ? 'already_verified' : 'success';
				email = data.user.email;
				setTimeout(() => void goto('/'), 2000);
			} catch (err) {
				if (err instanceof AuthApiError) {
					if (err.code === 'TOKEN_EXPIRED') status = 'expired';
					else if (err.code === 'TOKEN_USED') status = 'used';
					else if (err.code === 'INVALID_TOKEN') status = 'invalid';
					else status = 'error';
				} else {
					status = 'error';
				}
			}
		})();
	});
</script>

<svelte:head>
	<title>Verify email | Kainook</title>
</svelte:head>

<div class="flex min-h-screen items-center justify-center bg-[#F8FAFC] p-4">
	<div
		class="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"
	>
		{#if status === 'loading'}
			<div class="mb-4 text-5xl">⏳</div>
			<h1 class="mb-3 text-2xl font-bold text-slate-900">Verifying your email…</h1>
			<p class="text-slate-500">Please wait a moment.</p>
		{:else if status === 'success'}
			<div class="mb-4 text-5xl">🎉</div>
			<h1 class="mb-3 text-2xl font-bold text-slate-900">Email verified!</h1>
			<p class="text-slate-500">Welcome to Kainook! Redirecting you now…</p>
		{:else if status === 'already_verified'}
			<div class="mb-4 text-5xl">✅</div>
			<h1 class="mb-3 text-2xl font-bold text-slate-900">Already verified</h1>
			<p class="text-slate-500">You're already verified. Redirecting…</p>
		{:else if status === 'expired'}
			<div class="mb-4 text-5xl">⌛</div>
			<h1 class="mb-3 text-2xl font-bold text-slate-900">Link expired</h1>
			<div class="space-y-4">
				<p class="text-slate-500">
					Your verification link has expired (links are valid for 24 hours).
				</p>
				{#if email}
					<a
						href={`/auth/verify-pending?email=${encodeURIComponent(email)}`}
						class="inline-block rounded-lg bg-[#1D8D2B] px-6 py-2.5 font-semibold text-white"
					>
						Send a new link
					</a>
				{:else}
					<a href="/auth/login" class="inline-block font-semibold text-[#1D8D2B]">
						Back to Sign In
					</a>
				{/if}
			</div>
		{:else if status === 'used'}
			<div class="mb-4 text-5xl">🔒</div>
			<h1 class="mb-3 text-2xl font-bold text-slate-900">Link already used</h1>
			<div class="space-y-4">
				<p class="text-slate-500">This verification link has already been used.</p>
				<a href="/auth/login" class="inline-block font-semibold text-[#1D8D2B]">
					Sign in to your account
				</a>
			</div>
		{:else if status === 'invalid'}
			<div class="mb-4 text-5xl">❌</div>
			<h1 class="mb-3 text-2xl font-bold text-slate-900">Invalid link</h1>
			<div class="space-y-4">
				<p class="text-slate-500">This verification link is invalid.</p>
				<a href="/auth/register" class="inline-block font-semibold text-[#1D8D2B]">
					Create an account
				</a>
			</div>
		{:else}
			<div class="mb-4 text-5xl">⚠️</div>
			<h1 class="mb-3 text-2xl font-bold text-slate-900">Something went wrong</h1>
			<p class="text-slate-500">
				Please try clicking the link again, or
				<a href="/auth/login" class="font-semibold text-[#1D8D2B]">sign in</a>.
			</p>
		{/if}
	</div>
</div>
