// apps/web/app/listings/new/page.tsx
"use client";
import { useRouter } from "next/navigation";
import { useMutation } from "@tanstack/react-query";
import { listingApi } from "@/lib/listing-api";

const CATEGORIES = [
  { key: "hotel", title: "Hotel", description: "Rooms and suites in a hotel property", icon: "🏨" },
  { key: "apartment", title: "Apartment", description: "Self-contained units, studios, and apartments", icon: "🏠" },
  { key: "car", title: "Car Rental", description: "Vehicles available for daily or weekly hire", icon: "🚗" },
];

export default function NewListingPage() {
  const router = useRouter();

  const createMutation = useMutation({
    mutationFn: async (category: string) => {
      const res = await listingApi.post<{ data: { id: string } }>("/listings", { category });
      return res.data.data;
    },
    onSuccess: (data) => router.push(`/listings/${data.id}/edit`),
  });

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div className="w-full max-w-lg">
        <h1 className="text-2xl font-bold text-gray-900 mb-2">What type of listing?</h1>
        <p className="text-sm text-gray-500 mb-8">Choose the category that best describes your property or vehicle.</p>

        <div className="space-y-4">
          {CATEGORIES.map((cat) => (
            <button
              key={cat.key}
              onClick={() => createMutation.mutate(cat.key)}
              disabled={createMutation.isPending}
              className="w-full bg-white border border-gray-200 rounded-xl p-5 flex items-center gap-4 hover:border-primary hover:bg-primary/5 transition text-left disabled:opacity-60"
            >
              <span className="text-3xl">{cat.icon}</span>
              <div className="flex-1">
                <p className="font-semibold text-gray-900">{cat.title}</p>
                <p className="text-sm text-gray-500 mt-0.5">{cat.description}</p>
              </div>
              <span className="text-gray-400 text-xl">›</span>
            </button>
          ))}
        </div>

        {createMutation.isError && (
          <p className="mt-4 text-sm text-red-600 text-center">Failed to create listing. Please try again.</p>
        )}
      </div>
    </div>
  );
}

// apps/web-svelte/src/routes/(provider)/dashboard/listings/new/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { createListing } from '$lib/provider-api';

	const CATEGORIES = [
		{ key: 'hotel' as const, label: 'Hotel', icon: '🏨', desc: 'Rooms with nightly pricing and room types.' },
		{ key: 'apartment' as const, label: 'Home', icon: '🏠', desc: 'Apartment or residence, nightly pricing.' },
		{ key: 'car' as const, label: 'Car Rental', icon: '🚗', desc: 'Vehicles with daily pricing.' }
	];

	let creating = $state<'hotel' | 'apartment' | 'car' | null>(null);
	let error = $state('');

	async function handleCreate(category: 'hotel' | 'apartment' | 'car'): Promise<void> {
		creating = category;
		error = '';
		try {
			const res = await createListing(category);
			await goto(`/dashboard/listings/${res.id}/edit`);
		} catch {
			error = 'Could not create the listing. Please try again.';
			creating = null;
		}
	}
</script>

<div class="mx-auto max-w-2xl space-y-6">
	<div>
		<h1 class="text-3xl font-bold tracking-tight text-slate-900">Create a listing</h1>
		<p class="mt-1 text-sm text-slate-500">Choose the type of listing you want to add. You'll fill in the details next.</p>
	</div>

	{#if error}
		<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>
	{/if}

	<div class="grid gap-4">
		{#each CATEGORIES as c (c.key)}
			<button
				type="button"
				onclick={() => void handleCreate(c.key)}
				disabled={creating !== null}
				class="flex items-start gap-4 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:border-[#1D8D2B]/50 hover:shadow-md disabled:opacity-60"
			>
				<span class="text-3xl">{c.icon}</span>
				<div>
					<p class="font-bold text-slate-900">{c.label}</p>
					<p class="mt-0.5 text-sm text-slate-500">{c.desc}</p>
				</div>
				<span class="ml-auto text-sm font-semibold text-[#1D8D2B]">
					{creating === c.key ? 'Creating…' : 'Choose →'}
				</span>
			</button>
		{/each}
	</div>
</div>
