// apps/web-svelte/src/routes/(main)/(account)/recently-viewed/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { getRecentlyViewed, type RecentlyViewedListing } from '$lib/account-api';
	import { listingHref } from '$lib/listing-meta';
	import { formatMoney } from '$lib/currency-display';
	import ListingImage from '$lib/components/ListingImage.svelte';
	import type { ListingCategory } from '$lib/listing-api';

	let items = $state<RecentlyViewedListing[]>([]);
	let loading = $state(true);
	let error = $state<string | null>(null);

	function load(): void {
		loading = true;
		error = null;
		void (async () => {
			try {
				items = await getRecentlyViewed();
			} catch {
				error = 'Could not load your recently viewed listings. Please try again.';
			} finally {
				loading = false;
			}
		})();
	}

	onMount(load);

	function categoryLabel(cat: string | null | undefined): string {
		if (cat === 'car') return 'Car rental';
		if (cat === 'hotel') return 'Hotel';
		if (cat === 'apartment') return 'Apartment';
		return 'Listing';
	}

	function timeAgo(iso: string): string {
		const diff = Date.now() - new Date(iso).getTime();
		const mins = Math.floor(diff / 60000);
		if (mins < 1) return 'Just now';
		if (mins < 60) return `${mins}m ago`;
		const hours = Math.floor(mins / 60);
		if (hours < 24) return `${hours}h ago`;
		const days = Math.floor(hours / 24);
		if (days < 30) return `${days}d ago`;
		return new Date(iso).toLocaleDateString('en-GB', {
			day: 'numeric',
			month: 'short',
			year: 'numeric'
		});
	}
</script>

<div class="space-y-6">
	<a
		href="/"
		class="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-500 transition hover:text-[#0c2614]"
	>
		<svg
			class="h-4 w-4"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			viewBox="0 0 24 24"
		>
			<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
		</svg>
		Back to Home
	</a>
	<div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
		<div>
			<h1 class="text-3xl font-bold tracking-tight text-slate-900">Recently Viewed</h1>
			<p class="mt-1 text-sm text-slate-500">Listings you've been browsing lately.</p>
		</div>
		<button
			type="button"
			onclick={load}
			class="self-start rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600 transition hover:bg-slate-50 sm:self-auto"
		>
			Refresh
		</button>
	</div>

	{#if loading}
		<div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
			{#each [1, 2, 3, 4] as i (i)}
				<div
					class="animate-pulse overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"
				>
					<div class="h-44 bg-slate-100"></div>
					<div class="space-y-2 p-4">
						<div class="h-4 w-3/4 rounded bg-slate-100"></div>
						<div class="h-3 w-1/2 rounded bg-slate-100"></div>
					</div>
				</div>
			{/each}
		</div>
	{:else if error}
		<div class="rounded-2xl border border-red-200 bg-red-50 p-8 text-center">
			<p class="text-sm text-red-600">{error}</p>
			<button
				type="button"
				onclick={load}
				class="mt-4 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700 transition hover:bg-slate-50"
			>
				Try Again
			</button>
		</div>
	{:else if items.length === 0}
		<div class="rounded-2xl border border-slate-100 bg-white p-12 text-center shadow-sm">
			<div
				class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-[#f0fdf4] text-emerald-600"
			>
				<svg
					class="h-8 w-8"
					fill="none"
					stroke="currentColor"
					stroke-width="1.8"
					viewBox="0 0 24 24"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"
					/>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
					/>
				</svg>
			</div>
			<h3 class="text-lg font-bold text-slate-800">Nothing here yet</h3>
			<p class="mx-auto mt-2 max-w-sm text-sm text-slate-500">
				Browse some listings and they'll show up here so you can pick up where you left off.
			</p>
			<a
				href="/"
				class="mt-6 inline-block rounded-full bg-[#0c2614] px-6 py-2.5 text-sm font-semibold text-white transition hover:bg-[#081b0d]"
			>
				Explore Listings
			</a>
		</div>
	{:else}
		<div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
			{#each items as item (item.listingId)}
				{@const l = item.listing}
				{#if l}
					<div
						role="link"
						tabindex="0"
						onclick={() => void goto(listingHref(l.category, l.id))}
						onkeydown={(e) => {
							if (e.key === 'Enter' || e.key === ' ') {
								e.preventDefault();
								void goto(listingHref(l.category, l.id));
							}
						}}
						class="group cursor-pointer overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-[#1D8D2B]/40 hover:shadow-md"
					>
						<div class="relative h-44 overflow-hidden">
							<ListingImage
								src={l.primaryPhotoUrl}
								alt={l.title}
								category={(l.category as ListingCategory) ?? 'hotel'}
								class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
							/>
							<span
								class="absolute top-3 left-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold text-slate-700 uppercase backdrop-blur-sm"
							>
								{categoryLabel(l.category)}
							</span>
							<span
								class="absolute right-3 bottom-3 rounded-full bg-[#0c2614]/80 px-2.5 py-1 text-[10px] font-semibold text-white backdrop-blur-sm"
							>
								{timeAgo(item.viewedAt)}
							</span>
						</div>
						<div class="p-4">
							<h3 class="truncate text-sm font-bold text-slate-900">{l.title}</h3>
							<p class="mt-0.5 truncate text-xs text-slate-500">
								{[l.city, l.countryCode].filter(Boolean).join(', ') || '—'}
							</p>
							<div class="mt-3 flex items-center justify-between gap-2">
								<p class="text-sm font-bold text-slate-900">
									{l.nightlyRate != null
										? `${formatMoney(l.nightlyRate, l.currency ?? 'KES')}/night`
										: '—'}
								</p>
								<span
									class="rounded-lg border border-slate-200 px-3 py-1 text-[11px] font-semibold text-[#0c2614] transition group-hover:border-[#1D8D2B] group-hover:text-[#1D8D2B]"
								>
									View
								</span>
							</div>
						</div>
					</div>
				{/if}
			{/each}
		</div>
	{/if}
</div>

// apps/web/app/traveller/recently-viewed/page.tsx
"use client";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Clock, ArrowLeft, Search } from "lucide-react";
import { useAuthStore } from "@/stores/auth";
import { fetchRecentlyViewed } from "@/services/traveller";
import type { RecentlyViewedItem } from "@/services/traveller";
import ListingImage from "../components/ListingImage";

const CAT_LABEL: Record<string, string> = {
  hotel: "Hotel",
  apartment: "Apartment",
  car: "Car Rental",
};

function timeAgo(isoDate: string): string {
  const diff = Date.now() - new Date(isoDate).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  return `${days}d ago`;
}

export default function RecentlyViewedPage() {
  const router = useRouter();
  const { isAuthenticated, _hasHydrated } = useAuthStore();
  const [items, setItems] = useState<RecentlyViewedItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!_hasHydrated) return;
    if (!isAuthenticated) {
      router.replace("/auth/login");
      return;
    }
    fetchRecentlyViewed()
      .then(setItems)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [_hasHydrated, isAuthenticated]);

  if (!_hasHydrated || loading) {
    return (
      <div className="min-h-screen bg-[#F8FAFC] flex items-center justify-center">
        <div className="animate-spin h-10 w-10 border-4 border-[#1D8D2B] border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#F8FAFC] text-slate-800">
      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-8">
        {/* Page header */}
        <div className="flex items-center gap-4 mb-8">
          <Link
            href="/traveller"
            className="flex items-center gap-1.5 text-xs font-bold text-slate-500 hover:text-[#1D8D2B] transition uppercase tracking-wide"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back
          </Link>
          <div>
            <h1 className="text-2xl font-serif font-bold text-slate-900 flex items-center gap-2">
              <Clock className="w-5 h-5 text-[#1D8D2B]" />
              Recently Viewed
            </h1>
            {!loading && (
              <p className="text-sm text-slate-500 mt-0.5">
                {items.length} {items.length === 1 ? "listing" : "listings"} you recently explored
              </p>
            )}
          </div>
        </div>

        {items.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-24 text-center gap-4">
            <div className="w-16 h-16 rounded-full bg-slate-100 flex items-center justify-center">
              <Clock className="w-7 h-7 text-slate-300" />
            </div>
            <div>
              <p className="font-semibold text-slate-700 text-lg">Nothing viewed yet</p>
              <p className="text-slate-400 text-sm mt-1">Listings you open will appear here.</p>
            </div>
            <Link
              href="/traveller"
              className="mt-2 inline-flex items-center gap-2 px-5 py-2.5 bg-[#0c2614] text-white text-sm font-semibold rounded-full hover:bg-[#1D8D2B] transition"
            >
              <Search className="w-4 h-4" />
              Explore Listings
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {items.map((item) => {
              const l = item.listing;
              const isCar = l.category === "car";
              return (
                <div
                  key={item.listingId}
                  className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-all"
                >
                  {/* Image */}
                  <div className="aspect-[4/3] relative overflow-hidden bg-slate-100">
                    <ListingImage
                      listingId={l.id}
                      alt={l.title}
                      className="w-full h-full object-cover hover:scale-105 transition duration-500"
                    />
                    <span className="absolute top-3 left-3 bg-[#024622]/90 text-white text-[9px] font-semibold uppercase tracking-widest px-2.5 py-1 rounded-full">
                      {CAT_LABEL[l.category] ?? l.category}
                    </span>
                    <span className="absolute top-3 right-3 bg-black/50 backdrop-blur-sm text-white text-[9px] font-medium px-2 py-1 rounded-full">
                      {timeAgo(item.viewedAt)}
                    </span>
                  </div>

                  {/* Body */}
                  <div className="p-4">
                    <h3 className="font-semibold text-sm text-slate-900 line-clamp-1">{l.title}</h3>
                    {l.city && (
                      <p className="text-[10px] text-slate-400 mt-0.5 flex items-center gap-1">
                        <svg className="w-3 h-3 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        {l.city}
                      </p>
                    )}
                    <div className="flex items-center justify-between mt-3 pt-3 border-t border-slate-100">
                      <div>
                        <p className="text-[9px] uppercase font-bold text-slate-400 tracking-widest">Per {isCar ? "day" : "night"}</p>
                        <p className="text-base font-bold text-[#024622]">
                          {l.currency ?? "KES"} {l.nightlyRate ? l.nightlyRate.toLocaleString() : "—"}
                        </p>
                      </div>
                      <Link
                        href={`/listings/${l.id}`}
                        className="text-[11px] font-semibold px-3 py-1.5 rounded-xl bg-[#0c2614] text-white hover:bg-[#1D8D2B] transition"
                      >
                        View
                      </Link>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
