// apps/web-svelte/src/routes/(main)/(account)/reviews/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { getMyReviews, submitReview, type MyReview } from '$lib/account-api';
	import { readReviewContext, clearReviewContext } from '$lib/review-context';
	import { formatDate, cn } from '$lib/utils';

	// A ?bookingId/?listingName (or a stored post-checkout context) makes the
	// "Leave a review" form eligible for that completed booking.
	const context = $derived(readReviewContext());
	const bookingId = $derived(page.url.searchParams.get('bookingId') ?? context?.bookingId ?? '');
	const listingId = $derived(page.url.searchParams.get('listingId') ?? context?.listingId ?? '');
	const listingName = $derived(
		page.url.searchParams.get('listingName') ?? context?.listingName ?? ''
	);

	let reviews = $state<MyReview[]>([]);
	let loading = $state(true);
	let error = $state(false);

	let rating = $state(0);
	let title = $state('');
	let body = $state('');
	let submitting = $state(false);
	let submitError = $state<string | null>(null);
	let submittedOk = $state(false);

	const RATING_LABELS = ['Poor', 'Fair', 'Good', 'Very good', 'Excellent'];

	function load(): void {
		loading = true;
		error = false;
		void (async () => {
			try {
				reviews = await getMyReviews();
			} catch {
				error = true;
			} finally {
				loading = false;
			}
		})();
	}

	onMount(() => {
		load();
		// Keep the list fresh while the page is open.
		const timer = setInterval(load, 30_000);
		return () => clearInterval(timer);
	});

	const average = $derived(
		reviews.length ? reviews.reduce((s, r) => s + r.rating, 0) / reviews.length : 0
	);
	const replies = $derived(reviews.filter((r) => r.providerReply).length);
	const hidden = $derived(reviews.filter((r) => r.isHidden).length);

	function handleSubmit(): void {
		if (rating < 1) {
			submitError = 'Please select a star rating.';
			return;
		}
		if (!bookingId) {
			submitError = 'No booking selected for this review.';
			return;
		}
		submitError = null;
		submitting = true;
		void (async () => {
			try {
				await submitReview({
					bookingId,
					rating,
					title: title.trim() || undefined,
					body: body.trim() || undefined
				});
				submittedOk = true;
				title = '';
				body = '';
				clearReviewContext();
				load();
			} catch (e) {
				submitError = (e as Error).message ?? 'Could not submit your review.';
			} finally {
				submitting = false;
			}
		})();
	}
</script>

<div class="space-y-6">
	<div class="rounded-2xl border border-emerald-100 bg-white p-6 shadow-sm">
		<p class="text-xs font-semibold tracking-[0.28em] text-emerald-700 uppercase">
			Traveller reviews
		</p>
		<h1 class="mt-1 text-3xl font-bold text-slate-950">My Reviews</h1>
		<p class="mt-1 text-sm text-slate-500">
			Share your experience and see what hosts have said back.
		</p>
	</div>

	{#if submittedOk}
		<div
			class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"
		>
			<p>Thanks! Your review has been submitted.</p>
			<button
				type="button"
				onclick={() => (submittedOk = false)}
				class="mt-1 text-xs underline opacity-70 hover:opacity-100"
			>
				Dismiss
			</button>
		</div>
	{/if}

	<div class="grid gap-6 xl:grid-cols-[380px_1fr]">
		<!-- Leave a review -->
		<div class="h-fit rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm">
			<h3 class="text-lg font-bold text-slate-900">Leave a review</h3>

			{#if bookingId}
				<div class="mt-4 rounded-xl border border-emerald-200 bg-emerald-50/60 p-4">
					<p class="font-mono text-[11px] font-semibold text-slate-400">
						Booking {bookingId.slice(0, 8).toUpperCase()}
						{#if listingId}
							· Listing {listingId.replace(/-/g, '').slice(0, 8).toUpperCase()}
						{/if}
					</p>
					<p class="mt-1 flex items-center gap-2 text-sm font-semibold text-slate-800">
						<span class="rounded-full bg-[#16a34a] px-2 py-0.5 text-[10px] font-bold text-white"
							>ELIGIBLE</span
						>
						<span class="truncate">{listingName || 'This booking'}</span>
					</p>
				</div>

				<form
					onsubmit={(e) => {
						e.preventDefault();
						handleSubmit();
					}}
					class="mt-4 space-y-4"
				>
					<div>
						<span class="mb-1.5 block text-sm font-medium text-slate-700">Rating</span>
						<div class="flex items-center gap-1" role="radiogroup" aria-label="Rating">
							{#each [1, 2, 3, 4, 5] as i (i)}
								<button
									type="button"
									onclick={() => (rating = i)}
									role="radio"
									aria-checked={rating === i}
									aria-label={`${i} star${i !== 1 ? 's' : ''}`}
									class={cn(
										'text-2xl transition',
										i <= rating ? 'text-amber-400' : 'text-slate-300 hover:text-amber-300'
									)}
								>
									★
								</button>
							{/each}
							<span class="ml-2 text-sm font-semibold text-slate-500">
								{rating > 0 ? RATING_LABELS[rating - 1] : 'Tap to rate'}
							</span>
						</div>
					</div>

					<div>
						<label for="review-title" class="mb-1.5 block text-sm font-medium text-slate-700"
							>Title</label
						>
						<input
							id="review-title"
							bind:value={title}
							maxlength="100"
							placeholder="A short headline (optional)"
							class="w-full rounded-xl border border-slate-200 bg-[#f6fdf8] px-4 py-2.5 text-sm transition focus:border-[#1D8D2B] focus:ring-2 focus:ring-[#1D8D2B]/25 focus:outline-none"
						/>
					</div>

					<div>
						<label for="review-body" class="mb-1.5 block text-sm font-medium text-slate-700"
							>Review</label
						>
						<textarea
							id="review-body"
							bind:value={body}
							maxlength="2000"
							rows="4"
							placeholder="Tell others about your stay (optional)"
							class="w-full resize-none rounded-xl border border-slate-200 bg-[#f6fdf8] px-4 py-2.5 text-sm transition focus:border-[#1D8D2B] focus:ring-2 focus:ring-[#1D8D2B]/25 focus:outline-none"
						></textarea>
						<p class="mt-1 text-right text-xs text-slate-400">{body.length}/2000</p>
					</div>

					{#if submitError}
						<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3">
							<p class="text-sm text-red-600">{submitError}</p>
						</div>
					{/if}

					<button
						type="submit"
						disabled={submitting}
						class="flex w-full items-center justify-center gap-2 rounded-xl bg-[#16a34a] py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-[#15803d] disabled:cursor-not-allowed disabled:opacity-60"
					>
						{#if submitting}
							<span
								class="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"
							></span>
						{/if}
						Submit review
					</button>
					<p class="text-center text-xs text-slate-400">
						Only completed bookings within the review window can be reviewed.
					</p>
				</form>
			{:else}
				<div class="mt-4 rounded-2xl border border-slate-200 bg-slate-50/60 p-6 text-center">
					<div
						class="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-slate-100 text-slate-400"
					>
						<svg
							class="h-6 w-6"
							fill="none"
							stroke="currentColor"
							stroke-width="1.8"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"
							/>
						</svg>
					</div>
					<p class="text-sm font-semibold text-slate-600">No review link available</p>
					<p class="mx-auto mt-1 max-w-xs text-xs text-slate-500">
						Open a completed booking and use "Leave Review" to write one.
					</p>
					<a
						href="/bookings"
						class="mt-4 inline-block rounded-full border border-slate-200 bg-white px-5 py-2 text-xs font-semibold text-slate-700 transition hover:bg-slate-50"
					>
						My Reservations
					</a>
				</div>
			{/if}
		</div>

		<!-- My reviews -->
		<div class="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm">
			<div class="flex items-center justify-between gap-4">
				<h3 class="text-lg font-bold text-slate-900">My reviews</h3>
				<button
					type="button"
					onclick={load}
					class="rounded-xl border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600 transition hover:bg-slate-50"
				>
					Refresh
				</button>
			</div>

			{#if !loading}
				<div
					class="mt-4 grid grid-cols-4 gap-3 rounded-2xl border border-slate-200 bg-slate-50/60 p-4"
				>
					<div class="text-center">
						<p class="text-xl font-bold text-slate-900">{reviews.length}</p>
						<p class="text-[11px] font-semibold tracking-wide text-slate-400 uppercase">Total</p>
					</div>
					<div class="text-center">
						<p class="text-xl font-bold text-slate-900">
							{average ? average.toFixed(1) : '—'}
							<span class="text-amber-400">★</span>
						</p>
						<p class="text-[11px] font-semibold tracking-wide text-slate-400 uppercase">Average</p>
					</div>
					<div class="text-center">
						<p class="text-xl font-bold text-slate-900">{replies}</p>
						<p class="text-[11px] font-semibold tracking-wide text-slate-400 uppercase">Replies</p>
					</div>
					<div class="text-center">
						<p class="text-xl font-bold text-slate-900">{hidden}</p>
						<p class="text-[11px] font-semibold tracking-wide text-slate-400 uppercase">Hidden</p>
					</div>
				</div>
			{/if}

			{#if loading}
				<div class="mt-4 space-y-4">
					{#each [1, 2] as i (i)}
						<div class="animate-pulse rounded-2xl border border-slate-100 p-4">
							<div class="h-4 w-1/3 rounded bg-slate-100"></div>
							<div class="mt-2 h-3 w-2/3 rounded bg-slate-100"></div>
						</div>
					{/each}
				</div>
			{:else if error}
				<div class="mt-4 rounded-2xl border border-red-200 bg-red-50 p-6 text-center">
					<p class="text-sm text-red-600">Could not load your reviews.</p>
					<button
						type="button"
						onclick={load}
						class="mt-3 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700 transition hover:bg-slate-50"
					>
						Try Again
					</button>
				</div>
			{:else if reviews.length === 0}
				<div class="mt-4 rounded-2xl border border-slate-100 p-8 text-center">
					<p class="text-sm text-slate-500">You haven't written any reviews yet.</p>
				</div>
			{:else}
				<div class="mt-4 space-y-4">
					{#each [...reviews].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()) as r (r.id)}
						<div class="rounded-2xl border border-slate-200 p-4">
							<div class="flex items-start justify-between gap-3">
								<div>
									<p class="text-sm font-bold text-slate-900">{r.listingName}</p>
									<p class="mt-0.5 font-mono text-[11px] text-slate-400">
										Booking {r.bookingId.slice(0, 8).toUpperCase()} · {formatDate(r.createdAt)}
									</p>
								</div>
								<div class="flex shrink-0 items-center gap-1">
									{#each [1, 2, 3, 4, 5] as i (i)}
										<span class={i <= r.rating ? 'text-amber-400' : 'text-slate-200'}>★</span>
									{/each}
								</div>
							</div>
							{#if r.title}
								<p class="mt-2 text-sm font-semibold text-slate-800">{r.title}</p>
							{/if}
							{#if r.body}
								<p class="mt-1 text-sm text-slate-600">{r.body}</p>
							{/if}
							<div class="mt-2 flex flex-wrap items-center gap-2">
								{#if r.isHidden}
									<span
										class="rounded-full border border-slate-200 bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-500"
									>
										Hidden
									</span>
								{/if}
								{#if r.providerReply}
									<span
										class="rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-semibold text-emerald-700"
									>
										Provider replied
									</span>
								{/if}
							</div>
							{#if r.providerReply}
								<div class="mt-3 rounded-xl border border-green-200 bg-green-50 p-3">
									<p class="text-xs font-bold text-green-800">Provider reply</p>
									{#if r.providerRepliedAt}
										<p class="mt-0.5 text-[11px] text-green-600">
											{formatDate(r.providerRepliedAt)}
										</p>
									{/if}
									<p class="mt-1 text-sm text-green-900">{r.providerReply}</p>
								</div>
							{/if}
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>

// apps/web/app/traveller/reviews/page.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  RefreshCw,
  Star,
} from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, SectionHeader } from "@/components/ui/Card";
import { Input, Textarea } from "@/components/ui/Input";
import { Skeleton } from "@/components/ui/Skeleton";
import { RatingStars } from "@/components/charts/Charts";
import { cn, formatDate } from "@/lib/utils";
import {
  clearLatestReviewContext,
  fetchMyReviews,
  getApiErrorMessage,
  readLatestReviewContext,
  submitTravellerReview,
  TRAVELLER_REVIEW_RATING_MAX,
  TRAVELLER_REVIEW_RATING_MIN,
  type LatestReviewContext,
  type MyReview,
} from "@/services/traveller";

function shortId(value?: string | null) {
  return value ? value.replace(/-/g, "").slice(0, 8).toUpperCase() : "—";
}

const RATING_LABELS = {
  1: "Poor",
  2: "Fair",
  3: "Good",
  4: "Very good",
  5: "Excellent",
} as const;

function ReviewSkeleton() {
  return (
    <div className="space-y-4">
      {Array.from({ length: 3 }).map((_, index) => (
        <Card key={index} className="border-slate-200/80 bg-white/95 shadow-[0_12px_40px_rgba(15,23,42,0.06)]" padding="lg">
          <div className="space-y-4">
            <div className="flex items-center justify-between gap-3">
              <div className="space-y-2">
                <Skeleton className="h-4 w-32" />
                <Skeleton className="h-3 w-24" />
              </div>
              <Skeleton className="h-5 w-20 rounded-full" />
            </div>
            <Skeleton className="h-4 w-2/3" />
            <Skeleton className="h-16 w-full" />
          </div>
        </Card>
      ))}
    </div>
  );
}

function EmptyReviewsState({ title, message }: { title: string; message: string }) {
  return (
    <Card className="border-slate-200/80 bg-white/95 shadow-[0_12px_40px_rgba(15,23,42,0.06)]" padding="lg">
      <div className="flex min-h-[220px] flex-col items-center justify-center text-center">
        <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-slate-400">
          <Star className="h-7 w-7" />
        </div>
        <p className="mt-4 font-semibold text-slate-950">{title}</p>
        <p className="mt-1 max-w-md text-sm leading-6 text-slate-500">{message}</p>
      </div>
    </Card>
  );
}

function ReviewStarPicker({
  value,
  onChange,
}: {
  value: number;
  onChange: (value: number) => void;
}) {
  return (
    <div className="flex flex-wrap items-center gap-2">
      {Array.from({ length: 5 }).map((_, index) => {
        const star = index + 1;
        const active = star <= value;

        return (
          <button
            key={star}
            type="button"
            onClick={() => onChange(star)}
            aria-label={`${star} star rating`}
            className={cn(
              "flex h-11 w-11 items-center justify-center rounded-xl border transition",
              active
                ? "border-amber-300 bg-amber-50 text-amber-400"
                : "border-slate-200 bg-white text-slate-300 hover:border-amber-200 hover:bg-amber-50",
            )}
          >
            <Star className={cn("h-5 w-5", active && "fill-current")} />
          </button>
        );
      })}
      <div className="ml-1">
        <p className="text-sm font-semibold text-slate-950">{RATING_LABELS[value as keyof typeof RATING_LABELS]}</p>
        <p className="text-xs text-slate-400">{value}/{TRAVELLER_REVIEW_RATING_MAX}</p>
      </div>
    </div>
  );
}

function MyReviewCard({ review }: { review: MyReview }) {
  return (
    <Card className="border-slate-200/80 bg-white/95 shadow-[0_12px_40px_rgba(15,23,42,0.06)]" padding="lg">
      <div className="space-y-4">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div className="min-w-0 space-y-2">
            <div className="flex flex-wrap items-center gap-2">
              <Badge
                label={review.isHidden ? "hidden" : "visible"}
                variant={review.isHidden ? "warning" : "success"}
              />
              {review.providerReply && <Badge label="provider replied" variant="info" />}
              <span className="text-xs text-slate-400">{formatDate(review.createdAt)}</span>
            </div>
            <h3 className="text-base font-bold text-slate-950">{review.listingName}</h3>
            <p className="text-xs text-slate-500">Booking {shortId(review.bookingId)}</p>
          </div>
          <div className="flex items-center gap-2 rounded-2xl bg-amber-50 px-3 py-2">
            <RatingStars rating={review.rating} />
            <span className="text-sm font-semibold text-slate-950">{review.rating}/5</span>
          </div>
        </div>

        {review.title && <p className="text-sm font-semibold text-slate-950">{review.title}</p>}
        {review.body && (
          <p className={cn("text-sm leading-6 text-slate-600", !review.title && "pt-1")}>
            {review.body}
          </p>
        )}

        {review.providerReply && (
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50/70 p-4">
            <div className="flex items-center justify-between gap-3">
              <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-emerald-700">
                Provider reply
              </p>
              <span className="text-[11px] text-emerald-700">
                {review.providerRepliedAt ? formatDate(review.providerRepliedAt) : "Replied"}
              </span>
            </div>
            <p className="mt-2 text-sm leading-6 text-emerald-950">{review.providerReply}</p>
          </div>
        )}
      </div>
    </Card>
  );
}

export default function TravellerReviewsPage() {
  const queryClient = useQueryClient();
  const router = useRouter();
  const [latestContext, setLatestContext] = useState<LatestReviewContext | null>(null);
  const [rating, setRating] = useState(TRAVELLER_REVIEW_RATING_MAX);
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [formError, setFormError] = useState<string | null>(null);
  const [queryContext, setQueryContext] = useState({
    bookingId: "",
    listingId: "",
    listingName: "",
  });

  const {
    data: reviews = [],
    isLoading,
    isFetching,
    isError,
    error,
    refetch,
  } = useQuery({
    queryKey: ["traveller-my-reviews"],
    queryFn: fetchMyReviews,
    refetchInterval: 30_000,
    retry: false,
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      const params = new URLSearchParams(window.location.search);
      setQueryContext({
        bookingId: params.get("bookingId")?.trim() ?? "",
        listingId: params.get("listingId")?.trim() ?? "",
        listingName: params.get("listingName")?.trim() ?? "",
      });
    }
    setLatestContext(readLatestReviewContext());
  }, []);

  const bookingId = queryContext.bookingId || latestContext?.bookingId || "";
  const listingId = queryContext.listingId || latestContext?.listingId || "";
  const listingName = queryContext.listingName || latestContext?.listingName || "";
  const canReview = Boolean(bookingId);

  const submitMutation = useMutation({
    mutationFn: submitTravellerReview,
    onSuccess: (response) => {
      setSuccessMessage(response.message);
      setFormError(null);
      setRating(TRAVELLER_REVIEW_RATING_MAX);
      setTitle("");
      setBody("");
      setLatestContext(null);
      clearLatestReviewContext();
      queryClient.invalidateQueries({ queryKey: ["traveller-my-reviews"] });
      router.replace("/traveller/reviews", { scroll: false });
    },
    onError: (mutationError) => {
      setFormError(getApiErrorMessage(mutationError, "Unable to submit your review right now."));
    },
  });

  const sortedReviews = useMemo(
    () =>
      [...reviews].sort(
        (left, right) => new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime(),
      ),
    [reviews],
  );

  const stats = useMemo(() => {
    const total = sortedReviews.length;
    const average = total > 0
      ? sortedReviews.reduce((sum, review) => sum + review.rating, 0) / total
      : 0;
    const replied = sortedReviews.filter((review) => review.providerReply).length;
    const hidden = sortedReviews.filter((review) => review.isHidden).length;

    return { total, average, replied, hidden };
  }, [sortedReviews]);

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!canReview || submitMutation.isPending) return;

    const trimmedTitle = title.trim();
    const trimmedBody = body.trim();

    if (rating < TRAVELLER_REVIEW_RATING_MIN || rating > TRAVELLER_REVIEW_RATING_MAX) {
      setFormError("Please choose a rating between 1 and 5.");
      return;
    }

    submitMutation.mutate({
      bookingId,
      rating,
      title: trimmedTitle || undefined,
      body: trimmedBody || undefined,
    });
  };

  return (
    <>
      <div className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(16,185,129,0.12),_transparent_38%),linear-gradient(180deg,_#f8fafc_0%,_#f3f7f2_100%)]">
      <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <Card className="mb-6 border-emerald-100 bg-white/90 shadow-[0_18px_50px_rgba(15,23,42,0.08)] backdrop-blur" padding="lg">
          <div className="space-y-3">
            <p className="text-xs font-semibold uppercase tracking-[0.28em] text-emerald-700">Traveller reviews</p>
            <h1 className="text-3xl font-bold text-slate-950">My Reviews</h1>
            <p className="max-w-3xl text-sm leading-6 text-slate-500">
              Share feedback from your completed stays.
            </p>
          </div>
        </Card>

        {successMessage && (
          <div className="mb-4 flex items-start justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">
            <div className="flex items-center gap-2">
              <Star className="h-4 w-4" />
              <span>{successMessage}</span>
            </div>
            <button className="rounded-lg px-2 py-1 hover:bg-white/70" onClick={() => setSuccessMessage(null)}>
              Dismiss
            </button>
          </div>
        )}

        <div className="grid gap-4 xl:grid-cols-[380px_1fr]">
          <Card className="border-slate-200/80 bg-white/95 shadow-[0_12px_40px_rgba(15,23,42,0.06)]" padding="lg">
            <SectionHeader
              title="Leave a review"
              subtitle="Completed bookings only, and the booking link is kept locally after checkout."
            />

            {canReview ? (
              <form className="space-y-4" onSubmit={handleSubmit}>
                <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-400">Booking</p>
                      <p className="mt-1 font-mono text-sm font-semibold text-slate-950">{bookingId}</p>
                    </div>
                    <Badge label="eligible" variant="success" />
                  </div>
                  <div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500">
                    {listingName && <span>{listingName}</span>}
                    {listingId && <span>· Listing {shortId(listingId)}</span>}
                  </div>
                </div>

                <div className="space-y-2">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-400">Rating</p>
                  <ReviewStarPicker value={rating} onChange={setRating} />
                </div>

                <Input
                  label="Review title"
                  placeholder="A quick summary"
                  value={title}
                  onChange={(event) => setTitle(event.target.value)}
                  maxLength={100}
                  hint="Optional · 100 characters max"
                />

                <div className="space-y-1.5">
                  <Textarea
                    label="Review details"
                    placeholder="Tell future travellers what stood out, what felt special, or what could be better."
                    value={body}
                    onChange={(event) => setBody(event.target.value)}
                    rows={6}
                    maxLength={2000}
                  />
                  <p className="text-xs text-slate-400">Optional · {body.length}/2000 characters</p>
                </div>

                {formError && (
                  <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                    {formError}
                  </div>
                )}

                <Button
                  type="submit"
                  variant="success"
                  className="w-full"
                  loading={submitMutation.isPending}
                  disabled={!canReview || submitMutation.isPending}
                  icon={<Star />}
                >
                  Submit review
                </Button>

                <div className="rounded-2xl border border-emerald-200 bg-emerald-50/70 px-4 py-3 text-xs leading-6 text-emerald-800">
                  Reviews are only accepted for completed bookings within the backend review window. If your booking is too old or already reviewed, the API will reject the submission.
                </div>
              </form>
            ) : (
              <div className="flex min-h-[420px] flex-col items-center justify-center text-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-slate-400">
                  <ArrowLeft className="h-7 w-7" />
                </div>
                <p className="mt-4 font-semibold text-slate-950">No review link available</p>
                <p className="mt-1 max-w-sm text-sm leading-6 text-slate-500">
                  Open this page from a checkout confirmation or a review link from your most recent completed booking.
                </p>
                <div className="mt-5 flex flex-wrap items-center justify-center gap-2">
                  <Button variant="outline" onClick={() => router.push("/")}>
                    Browse listings
                  </Button>
                  <Button variant="ghost" onClick={() => router.push("/traveller/messages")}>
                    Open messages
                  </Button>
                </div>
              </div>
            )}
          </Card>

          <div className="space-y-4">
            <Card className="border-slate-200/80 bg-white/95 shadow-[0_12px_40px_rgba(15,23,42,0.06)]" padding="lg">
              <SectionHeader
                title="My reviews"
                subtitle={`${stats.total} submitted · ${stats.average ? stats.average.toFixed(1) : "0.0"} average rating`}
                action={
                  <Button
                    variant="outline"
                    icon={<RefreshCw />}
                    loading={isFetching && !isLoading}
                    onClick={() => refetch()}
                  >
                    Refresh
                  </Button>
                }
              />

              <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-400">Total</p>
                  <p className="mt-2 text-2xl font-bold text-slate-950">{stats.total}</p>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-400">Average</p>
                  <div className="mt-2 flex items-center gap-2">
                    <p className="text-2xl font-bold text-slate-950">{stats.average ? stats.average.toFixed(1) : "—"}</p>
                    <RatingStars rating={stats.average} />
                  </div>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-400">Replies</p>
                  <p className="mt-2 text-2xl font-bold text-slate-950">{stats.replied}</p>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-400">Hidden</p>
                  <p className="mt-2 text-2xl font-bold text-slate-950">{stats.hidden}</p>
                </div>
              </div>
            </Card>

            {isLoading ? (
              <ReviewSkeleton />
            ) : isError ? (
              <EmptyReviewsState
                title="Unable to load your reviews"
                message={getApiErrorMessage(error, "Please try again in a moment.")}
              />
            ) : sortedReviews.length === 0 ? (
              <EmptyReviewsState
                title="No reviews yet"
                message="Once you submit your first completed-stay review, it will show up here."
              />
            ) : (
              <div className="space-y-4">
                {sortedReviews.map((review) => (
                  <MyReviewCard key={review.id} review={review} />
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
    </>
  );
}
